/**
 * Multi-language support for Dhikr Counter App
 * Supports: Arabic, English, Thai, Indonesian, Urdu, Bengali, Turkish, Persian, Malay, French
 * Languages for countries with large Muslim populations
 */

export const LANGUAGES = {
  ar: {
    code: 'ar',
    name: 'العربية',
    dir: 'rtl',
    order: 1,
  },
  en: {
    code: 'en',
    name: 'English',
    dir: 'ltr',
    order: 2,
  },
  th: {
    code: 'th',
    name: 'ไทย',
    dir: 'ltr',
    order: 3,
  },
  id: {
    code: 'id',
    name: 'Indonesia',
    dir: 'ltr',
    order: 4,
  },
  ur: {
    code: 'ur',
    name: 'اردو',
    dir: 'rtl',
    order: 5,
  },
  bn: {
    code: 'bn',
    name: 'বাংলা',
    dir: 'ltr',
    order: 6,
  },
  tr: {
    code: 'tr',
    name: 'Türkçe',
    dir: 'ltr',
    order: 7,
  },
  fa: {
    code: 'fa',
    name: 'فارسی',
    dir: 'rtl',
    order: 8,
  },
  ms: {
    code: 'ms',
    name: 'Melayu',
    dir: 'ltr',
    order: 9,
  },
  fr: {
    code: 'fr',
    name: 'Français',
    dir: 'ltr',
    order: 10,
  },
};

export const TRANSLATIONS = {
  ar: {
    // Header
    appTitle: 'ADHKAR - أذكار',
    appSubtitle: 'احفظ أورادك اليومية بسهولة',
    
    // Dhikr selection
    selectDhikr: 'اختر نوع الذكر',
    
    // Dhikr types
    dhikr_subhanallah: 'سبحان الله',
    dhikr_alhamdulillah: 'الحمد لله',
    dhikr_allahuakbar: 'الله أكبر',
    dhikr_lailahaillallah: 'لا إله إلا الله',
    dhikr_astaghfirullah: 'أستغفر الله',
    dhikr_lahawla: 'لا حول ولا قوة إلا بالله',
    
    // Counter
    currentCount: 'العدد الحالي',
    
    // Main button
    mainButton: 'سَبِّح',
    mainButtonSub: 'اضغط للعد',
    
    // Control buttons
    resetCounter: 'إعادة تعيين العداد',
    viewStatistics: 'عرض الإحصائيات',
    clearAllData: 'مسح جميع البيانات',
    
    // Statistics
    statistics: 'الإحصائيات',
    totalAll: 'إجمالي جميع الأذكار',
    currentSession: 'الجلسة الحالية',
    mostUsed: 'الأكثر استخداماً',
    times: 'مرة',
    savedTotals: 'إجمالي الأذكار المحفوظة',
    session: 'جلسة حالية',
    percentage: '%',
    backToCounter: 'العودة للعداد',
    
    // Alerts
    resetTitle: 'إعادة تعيين العداد',
    resetMessage: 'هل تريد إعادة تعيين العداد الحالي لـ',
    resetConfirm: 'إعادة تعيين',
    cancel: 'إلغاء',
    clearTitle: 'مسح جميع البيانات',
    clearMessage: 'هل أنت متأكد من مسح جميع البيانات المحفوظة؟ لا يمكن التراجع عن هذا الإجراء.',
    clearConfirm: 'مسح الكل',
    success: 'تم',
    dataCleared: 'تم مسح جميع البيانات بنجاح',
    
    // Language
    selectLanguage: 'اختر اللغة',
    language: 'اللغة',
  },
  
  en: {
    // Header
    appTitle: 'ADHKAR',
    appSubtitle: 'Keep track of your daily prayers',
    
    // Dhikr selection
    selectDhikr: 'Select Dhikr Type',
    
    // Dhikr types
    dhikr_subhanallah: 'Subhan Allah (Glory be to Allah)',
    dhikr_alhamdulillah: 'Alhamdulillah (Praise be to Allah)',
    dhikr_allahuakbar: 'Allahu Akbar (Allah is Greatest)',
    dhikr_lailahaillallah: 'La ilaha illallah (No god but Allah)',
    dhikr_astaghfirullah: 'Astaghfirullah (I seek forgiveness)',
    dhikr_lahawla: 'La hawla wala quwwata illa billah',
    
    // Counter
    currentCount: 'Current Count',
    
    // Main button
    mainButton: 'Count',
    mainButtonSub: 'Tap to count',
    
    // Control buttons
    resetCounter: 'Reset Counter',
    viewStatistics: 'View Statistics',
    clearAllData: 'Clear All Data',
    
    // Statistics
    statistics: 'Statistics',
    totalAll: 'Total All Dhikr',
    currentSession: 'Current Session',
    mostUsed: 'Most Used',
    times: 'times',
    savedTotals: 'Saved Totals',
    session: 'current session',
    percentage: '%',
    backToCounter: 'Back to Counter',
    
    // Alerts
    resetTitle: 'Reset Counter',
    resetMessage: 'Do you want to reset the current counter for',
    resetConfirm: 'Reset',
    cancel: 'Cancel',
    clearTitle: 'Clear All Data',
    clearMessage: 'Are you sure you want to clear all saved data? This action cannot be undone.',
    clearConfirm: 'Clear All',
    success: 'Success',
    dataCleared: 'All data cleared successfully',
    
    // Language
    selectLanguage: 'Select Language',
    language: 'Language',
  },
  
  th: {
    // Header
    appTitle: 'ADHKAR - อัซการ์',
    appSubtitle: 'บันทึกการภาวนาประจำวันของคุณ',
    
    // Dhikr selection
    selectDhikr: 'เลือกประเภทซิกร์',
    
    // Dhikr types
    dhikr_subhanallah: 'ซุบฮานัลลอฮ์ (พระเจ้าทรงบริสุทธิ์)',
    dhikr_alhamdulillah: 'อัลฮัมดุลิลลาฮ์ (สรรเสริญพระเจ้า)',
    dhikr_allahuakbar: 'อัลลอฮุอักบัร (พระเจ้ายิ่งใหญ่ที่สุด)',
    dhikr_lailahaillallah: 'ลาอิลาฮะอิลลัลลอฮ์ (ไม่มีพระเจ้านอกจากอัลลอฮ์)',
    dhikr_astaghfirullah: 'อัสตัฆฟิรุลลอฮ์ (ขอการอภัย)',
    dhikr_lahawla: 'ลาเฮาละวะลากุ๊วะตะอิลลาบิลลาฮ์',
    
    // Counter
    currentCount: 'จำนวนปัจจุบัน',
    
    // Main button
    mainButton: 'นับ',
    mainButtonSub: 'แตะเพื่อนับ',
    
    // Control buttons
    resetCounter: 'รีเซ็ตตัวนับ',
    viewStatistics: 'ดูสถิติ',
    clearAllData: 'ลบข้อมูลทั้งหมด',
    
    // Statistics
    statistics: 'สถิติ',
    totalAll: 'ซิกร์ทั้งหมด',
    currentSession: 'เซสชันปัจจุบัน',
    mostUsed: 'ใช้มากที่สุด',
    times: 'ครั้ง',
    savedTotals: 'ข้อมูลที่บันทึก',
    session: 'เซสชันปัจจุบัน',
    percentage: '%',
    backToCounter: 'กลับไปที่ตัวนับ',
    
    // Alerts
    resetTitle: 'รีเซ็ตตัวนับ',
    resetMessage: 'คุณต้องการรีเซ็ตตัวนับปัจจุบันสำหรับ',
    resetConfirm: 'รีเซ็ต',
    cancel: 'ยกเลิก',
    clearTitle: 'ลบข้อมูลทั้งหมด',
    clearMessage: 'คุณแน่ใจหรือไม่ว่าต้องการลบข้อมูลที่บันทึกทั้งหมด? การดำเนินการนี้ไม่สามารถย้อนกลับได้',
    clearConfirm: 'ลบทั้งหมด',
    success: 'สำเร็จ',
    dataCleared: 'ลบข้อมูลทั้งหมดเรียบร้อยแล้ว',
    
    // Language
    selectLanguage: 'เลือกภาษา',
    language: 'ภาษา',
  },
  
  id: {
    appTitle: 'ADHKAR',
    appSubtitle: 'Lacak dzikir harian Anda',
    selectDhikr: 'Pilih Jenis Dzikir',
    dhikr_subhanallah: 'Subhanallah',
    dhikr_alhamdulillah: 'Alhamdulillah',
    dhikr_allahuakbar: 'Allahu Akbar',
    dhikr_lailahaillallah: 'La ilaha illallah',
    dhikr_astaghfirullah: 'Astaghfirullah',
    dhikr_lahawla: 'La hawla wala quwwata illa billah',
    currentCount: 'Hitungan Saat Ini',
    mainButton: 'Hitung',
    mainButtonSub: 'Ketuk untuk menghitung',
    resetCounter: 'Atur Ulang',
    viewStatistics: 'Lihat Statistik',
    clearAllData: 'Hapus Semua',
    statistics: 'Statistik',
    totalAll: 'Total Semua',
    currentSession: 'Sesi Saat Ini',
    mostUsed: 'Paling Sering',
    times: 'kali',
    savedTotals: 'Total Tersimpan',
    session: 'sesi saat ini',
    percentage: '%',
    backToCounter: 'Kembali',
    resetTitle: 'Atur Ulang',
    resetMessage: 'Atur ulang penghitung untuk',
    resetConfirm: 'Atur Ulang',
    cancel: 'Batal',
    clearTitle: 'Hapus Semua',
    clearMessage: 'Hapus semua data?',
    clearConfirm: 'Hapus',
    success: 'Berhasil',
    dataCleared: 'Data dihapus',
    selectLanguage: 'Pilih Bahasa',
    language: 'Bahasa',
  },
  
  ur: {
    appTitle: 'ADHKAR',
    appSubtitle: 'روزانہ دعائیں',
    selectDhikr: 'ذکر منتخب کریں',
    dhikr_subhanallah: 'سبحان اللہ',
    dhikr_alhamdulillah: 'الحمد للہ',
    dhikr_allahuakbar: 'اللہ اکبر',
    dhikr_lailahaillallah: 'لا الہ الا اللہ',
    dhikr_astaghfirullah: 'استغفر اللہ',
    dhikr_lahawla: 'لا حول ولا قوۃ الا باللہ',
    currentCount: 'موجودہ شمار',
    mainButton: 'شمار',
    mainButtonSub: 'ٹیپ کریں',
    resetCounter: 'ری سیٹ',
    viewStatistics: 'شماریات',
    clearAllData: 'سب صاف کریں',
    statistics: 'شماریات',
    totalAll: 'کل',
    currentSession: 'موجودہ',
    mostUsed: 'زیادہ',
    times: 'بار',
    savedTotals: 'محفوظ',
    session: 'موجودہ',
    percentage: '%',
    backToCounter: 'واپس',
    resetTitle: 'ری سیٹ',
    resetMessage: 'ری سیٹ کریں',
    resetConfirm: 'ری سیٹ',
    cancel: 'منسوخ',
    clearTitle: 'صاف کریں',
    clearMessage: 'سب صاف کریں؟',
    clearConfirm: 'صاف کریں',
    success: 'کامیابی',
    dataCleared: 'صاف ہو گیا',
    selectLanguage: 'زبان',
    language: 'زبان',
  },
  
  bn: {
    appTitle: 'ADHKAR',
    appSubtitle: 'দৈনিক প্রার্থনা',
    selectDhikr: 'জিকির নির্বাচন করুন',
    dhikr_subhanallah: 'সুবহানাল্লাহ',
    dhikr_alhamdulillah: 'আলহামদুলিল্লাহ',
    dhikr_allahuakbar: 'আল্লাহু আকবার',
    dhikr_lailahaillallah: 'লা ইলাহা ইল্লাল্লাহ',
    dhikr_astaghfirullah: 'আস্তাগফিরুল্লাহ',
    dhikr_lahawla: 'লা হাওলা ওয়ালা কুওয়াতা',
    currentCount: 'বর্তমান গণনা',
    mainButton: 'গণনা',
    mainButtonSub: 'ট্যাপ করুন',
    resetCounter: 'রিসেট',
    viewStatistics: 'পরিসংখ্যান',
    clearAllData: 'সব মুছুন',
    statistics: 'পরিসংখ্যান',
    totalAll: 'মোট',
    currentSession: 'বর্তমান',
    mostUsed: 'বেশি ব্যবহৃত',
    times: 'বার',
    savedTotals: 'সংরক্ষিত',
    session: 'বর্তমান',
    percentage: '%',
    backToCounter: 'ফিরে যান',
    resetTitle: 'রিসেট',
    resetMessage: 'রিসেট করুন',
    resetConfirm: 'রিসেট',
    cancel: 'বাতিল',
    clearTitle: 'মুছুন',
    clearMessage: 'সব মুছুন?',
    clearConfirm: 'মুছুন',
    success: 'সফল',
    dataCleared: 'মুছে ফেলা হয়েছে',
    selectLanguage: 'ভাষা',
    language: 'ভাষা',
  },
  
  tr: {
    appTitle: 'ADHKAR',
    appSubtitle: 'Günlük dualar',
    selectDhikr: 'Zikir Seçin',
    dhikr_subhanallah: 'Sübhanallah',
    dhikr_alhamdulillah: 'Elhamdülillah',
    dhikr_allahuakbar: 'Allahu Ekber',
    dhikr_lailahaillallah: 'La ilahe illallah',
    dhikr_astaghfirullah: 'Estağfirullah',
    dhikr_lahawla: 'La havle vela kuvvete',
    currentCount: 'Mevcut Sayım',
    mainButton: 'Say',
    mainButtonSub: 'Dokunun',
    resetCounter: 'Sıfırla',
    viewStatistics: 'İstatistikler',
    clearAllData: 'Tümünü Temizle',
    statistics: 'İstatistikler',
    totalAll: 'Toplam',
    currentSession: 'Mevcut',
    mostUsed: 'En Çok',
    times: 'kez',
    savedTotals: 'Kaydedilmiş',
    session: 'mevcut',
    percentage: '%',
    backToCounter: 'Geri Dön',
    resetTitle: 'Sıfırla',
    resetMessage: 'Sıfırla',
    resetConfirm: 'Sıfırla',
    cancel: 'İptal',
    clearTitle: 'Temizle',
    clearMessage: 'Tümünü temizle?',
    clearConfirm: 'Temizle',
    success: 'Başarılı',
    dataCleared: 'Temizlendi',
    selectLanguage: 'Dil',
    language: 'Dil',
  },
  
  fa: {
    appTitle: 'ADHKAR',
    appSubtitle: 'دعاهای روزانه',
    selectDhikr: 'انتخاب ذکر',
    dhikr_subhanallah: 'سبحان الله',
    dhikr_alhamdulillah: 'الحمد لله',
    dhikr_allahuakbar: 'الله اکبر',
    dhikr_lailahaillallah: 'لا اله الا الله',
    dhikr_astaghfirullah: 'استغفرالله',
    dhikr_lahawla: 'لا حول ولا قوه',
    currentCount: 'شمارش فعلی',
    mainButton: 'شمارش',
    mainButtonSub: 'ضربه بزنید',
    resetCounter: 'بازنشانی',
    viewStatistics: 'آمار',
    clearAllData: 'پاک کردن',
    statistics: 'آمار',
    totalAll: 'مجموع',
    currentSession: 'فعلی',
    mostUsed: 'پرکاربرد',
    times: 'بار',
    savedTotals: 'ذخیره شده',
    session: 'فعلی',
    percentage: '%',
    backToCounter: 'بازگشت',
    resetTitle: 'بازنشانی',
    resetMessage: 'بازنشانی',
    resetConfirm: 'بازنشانی',
    cancel: 'لغو',
    clearTitle: 'پاک کردن',
    clearMessage: 'پاک کردن همه؟',
    clearConfirm: 'پاک کردن',
    success: 'موفق',
    dataCleared: 'پاک شد',
    selectLanguage: 'زبان',
    language: 'زبان',
  },
  
  ms: {
    appTitle: 'ADHKAR',
    appSubtitle: 'Doa harian',
    selectDhikr: 'Pilih Zikir',
    dhikr_subhanallah: 'Subhanallah',
    dhikr_alhamdulillah: 'Alhamdulillah',
    dhikr_allahuakbar: 'Allahu Akbar',
    dhikr_lailahaillallah: 'La ilaha illallah',
    dhikr_astaghfirullah: 'Astaghfirullah',
    dhikr_lahawla: 'La hawla wala quwwata',
    currentCount: 'Kiraan Semasa',
    mainButton: 'Kira',
    mainButtonSub: 'Tekan',
    resetCounter: 'Set Semula',
    viewStatistics: 'Statistik',
    clearAllData: 'Kosongkan',
    statistics: 'Statistik',
    totalAll: 'Jumlah',
    currentSession: 'Semasa',
    mostUsed: 'Kerap',
    times: 'kali',
    savedTotals: 'Tersimpan',
    session: 'semasa',
    percentage: '%',
    backToCounter: 'Kembali',
    resetTitle: 'Set Semula',
    resetMessage: 'Set semula',
    resetConfirm: 'Set Semula',
    cancel: 'Batal',
    clearTitle: 'Kosongkan',
    clearMessage: 'Kosongkan semua?',
    clearConfirm: 'Kosongkan',
    success: 'Berjaya',
    dataCleared: 'Dikosongkan',
    selectLanguage: 'Bahasa',
    language: 'Bahasa',
  },
  
  fr: {
    appTitle: 'ADHKAR',
    appSubtitle: 'Prières quotidiennes',
    selectDhikr: 'Sélectionnez Dhikr',
    dhikr_subhanallah: 'Subhan Allah',
    dhikr_alhamdulillah: 'Alhamdulillah',
    dhikr_allahuakbar: 'Allahu Akbar',
    dhikr_lailahaillallah: 'La ilaha illallah',
    dhikr_astaghfirullah: 'Astaghfirullah',
    dhikr_lahawla: 'La hawla wala quwwata',
    currentCount: 'Compte Actuel',
    mainButton: 'Compter',
    mainButtonSub: 'Appuyez',
    resetCounter: 'Réinitialiser',
    viewStatistics: 'Statistiques',
    clearAllData: 'Tout Effacer',
    statistics: 'Statistiques',
    totalAll: 'Total',
    currentSession: 'Actuel',
    mostUsed: 'Plus Utilisé',
    times: 'fois',
    savedTotals: 'Sauvegardés',
    session: 'actuel',
    percentage: '%',
    backToCounter: 'Retour',
    resetTitle: 'Réinitialiser',
    resetMessage: 'Réinitialiser',
    resetConfirm: 'Réinitialiser',
    cancel: 'Annuler',
    clearTitle: 'Effacer',
    clearMessage: 'Tout effacer?',
    clearConfirm: 'Effacer',
    success: 'Succès',
    dataCleared: 'Effacé',
    selectLanguage: 'Langue',
    language: 'Langue',
  },
};

// Dhikr list mapped to translation keys
export const ADHKAR_KEYS = [
  'dhikr_subhanallah',
  'dhikr_alhamdulillah',
  'dhikr_allahuakbar',
  'dhikr_lailahaillallah',
  'dhikr_astaghfirullah',
  'dhikr_lahawla',
];
